jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        System\UserBundle\Entity\User:
            algorithm:          sha512
            iterations:         1
            encode_as_base64:   false
    providers:
        delivery_user_provider:
            id: delivery.user_provider
        fos_userbundle:
            id: fos_user.user_manager        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_EMPLOYEE:    ROLE_USER

    
    firewalls:
        main:
            http-basic:     true
            pattern:        /.*
            form_login:
                check_path:     /login_check
                login_path:     /sign_in
                failure_path:   /sign_in
                always_use_default_target_path: true
                default_target_path: /backoffice/main
                provider:       delivery_user_provider
                use_referer: true
            anonymous:      ~
            security:       true
            logout:
                path:           /logout
                target:         /sign_in

    access_control:
        - { path: ^/profile, roles:  [ROLE_EMPLOYEE, ROLE_ADMIN] }
        - { path: ^/backoffice, roles: [ROLE_EMPLOYEE, ROLE_ADMIN] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
